services:
  node:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./:/usr/src/app
    # command: sh -c "cd ec-app && npm run start"
    command: sh -c "cd ec-app/ && npm install && while:; do sleep 10; done"
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8080:8080"
      - "8001:8001"
    environment:
      - CHOKIDAR_USEPOLLING=true
