services:
  node:
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "cd ec-app && npm run start"
    ports:
      - "3000:3000"
